# 1. Endereço do  banco no Render (sem a senha e usuário, formato JDBC)
spring.datasource.url=jdbc:postgresql://dpg-daospsbtqb8s73efo7vg-a.virginia-postgres.render.com:5432/perifericos

# 2. Usuário e Senha do link
spring.datasource.username=perifericos_user
spring.datasource.password=oKm1tvq0PZ7ol7ETDZFl9Oswk3l6bw6t

# 3. Mandar o Hibernate criar as tabelas sozinho!
spring.jpa.hibernate.ddl-auto=update

# 4. Informar qual é a linguagem SQL (Dialeto)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 5. Opcional: mostrar os comandos SQL no console
spring.jpa.show-sql=true